server:
  port: 0
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/naver_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: naver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.16:8761/eureka/
  instance:
    instance-id: cart-service
    prefer-ip-address: true
    ip-address: 192.168.0.16