server:
  port: 9002
spring:
  application:
    name: shopping-cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/naver_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    password: 1234
    username: naver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.80.38:8765/eureka/
#  instance:
#    instance-id: shopping-cart
#    prefer-ip-address: true
#    ip-address: 192.168.0.16